#!/bin/zsh

# completion
autoload -U compinit
compinit
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'

#colors
[ -f /etc/DIR_COLORS ] && eval $(dircolors -b /etc/DIR_COLORS)
export ZLSCOLORS="${LS_COLORS}"
zmodload  zsh/complist
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
autoload -U colors && colors

## Key bindings 
autoload zkbd 
# setup key accordingly 
[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line 
[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line 
[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode 
[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char 
[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history 
[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history 
[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char 
[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
# override stubborn keys
bindkey "^[[7~" beginning-of-line
bindkey "^[[8~" end-of-line

# correction
setopt correctall
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt autocd

# prompt
autoload -U promptinit
promptinit
prompt gentoo

export HISTSIZE=2000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

source '/usr/share/zsh/site-contrib/oh-my-zsh/templates/zshrc.zsh-template'
